# Base de datos ? viene de variable de entorno
spring.datasource.url=${postgres://avnadmin:AVNS_BHZV7ZiWT2ncOAZP37D@tutorspace-brahianrueda123-cd6c.i.aivencloud.com:22148/defaultdb?sslmode=require}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT ? viene de variable de entorno
jwt.secret=${dHV0b3JzcGFjZV9qd3Rfc2VjcmV0X2tleV8yMDI0X3Vjbw==}
jwt.expiration=86400000

# Puerto
server.port=8080