spring.application.name=TutorSpace_API

server.port=8080

spring.datasource.url=jdbc:postgresql://acela.proxy.rlwy.net:22833/railway
spring.datasource.username=postgres
spring.datasource.password=EXTFfSHQblEuEeJycdebOezLRFZlcRhU
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dHV0b3JzcGFjZV9qd3Rfc2VjcmV0X2tleV8yMDI0X3Vjbw==
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
