name: Deploy Backend

on:
  push:
    branches: [Develop]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy a Railway
        run: railway up --service tutorspaceapi --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}